### ISSUE TITLE
Fix image format issues for inputs to frame_merger

### ISSUE THREAD

**Issue by kpberry** [gtagency/buzzmobile#101]

**Comment by irapha** [comment]
Things included in this issue are some changes that were made in `odom_launch_test` but never had a PR for them (because we were debugging as we were testing).

https://github.com/gtagency/buzzmobile/compare/odom_launch_test?expand=1#diff-77edad01ecd5708046b743efdf602ef7R18

https://github.com/gtagency/buzzmobile/compare/odom_launch_test?expand=1#diff-9e78fa7700de7582ce3cc4cf9ca17dd8R61

This last one might not be helpful, because it was supposedly working before, but I have no clue why we are working with color images here and `mono8` everywhere else so please fix maybe?

**Comment by diptodip** [comment]
Fixed by #132.
