### ISSUE TITLE
Make setup.py file in project root

### ISSUE THREAD

**Issue by kpberry** [gtagency/buzzmobile#61]

**Comment by joshuamorton** [comment]
I started this on a (now deleted) branch. I can push it again as a starting point if you'd like.

Also what's the goal of setup.py in this case

**Comment by irapha** [comment]
The goal is to install python deps automatically. Sorry if I deleted your branch, I thought I was only deleting stale branches. In any case, @kpberry got started on this with some of our real deps in `launch` branch

**Comment by joshuamorton** [comment]
No, I'm pretty sure I deleted it a while back (and my goal was for a ros package, so different goals there I think).

**Comment by joshuamorton** [comment]
On second thought, can we (either here or in another issue) change this to "automate the deployment process" such that we factor out everything into an install.sh that runs setup.py, etc. and so that you can git clone and ./install.sh and run. This way we have a combined deploy process across CI, live environment, and dev environments, that's really easy to use.

**Comment by irapha** [comment]
What do you mean a ros package? We still have `package.xml`, but that's not a python thing. Oh do you mean that the goal was to make all of buzzmobile one package so that relative imports would work? I don't think we need that anymore because there aren't shared deps, and shared constants are rosparams now.

I agree that deployment needs to get better. Can you add a low-priority issue for Spring Carnival?

**Comment by joshuamorton** [comment]
Exactly, that's what I mean. And yea.
